FROM quay.io/wenxiang/pypy-wheel-builder

ENV LIBRDKAFKA_VERSION 0.11.4
ENV OPENSSL_VER=1.0.2o

RUN apt-get install -y zlib1g-dev

COPY scripts/install-libs.sh /tmp
RUN /tmp/install-libs.sh

WORKDIR /app

